#!/bin/sh
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type RAG
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 1NNSpatial
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 2NNSpatial
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 4NNSpatial
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 8NNSpatial
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 16NNSpatial
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 1NNFeatures
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 2NNFeatures
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 4NNFeatures
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 8NNFeatures
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 16NNFeatures

python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type RAG
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 1NNSpatial
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 2NNSpatial
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 4NNSpatial
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 8NNSpatial
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 16NNSpatial
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 1NNFeatures
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 2NNFeatures
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 4NNFeatures
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 8NNFeatures
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 16NNFeatures

python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type RAG
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 1NNSpatial
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 2NNSpatial
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 4NNSpatial
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 8NNSpatial
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 16NNSpatial
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 1NNFeatures
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 2NNFeatures
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 4NNFeatures
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 8NNFeatures
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 16NNFeatures

python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type RAG
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 1NNSpatial
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 2NNSpatial
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 4NNSpatial
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 8NNSpatial
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 16NNSpatial
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 1NNFeatures
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 2NNFeatures
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 4NNFeatures
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 8NNFeatures
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 16NNFeatures

python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type RAG
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 1NNSpatial
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 2NNSpatial
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 4NNSpatial
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 8NNSpatial
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 16NNSpatial
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 1NNFeatures
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 2NNFeatures
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 4NNFeatures
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 8NNFeatures
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 16NNFeatures
