#!/bin/sh 
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type RAG --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 1NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 2NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 4NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 8NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 16NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 1NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 2NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 4NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 8NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset mnist -f GAT/mnist-graph-types --graph_type 16NNFeatures --n_heads 1

python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type RAG --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 1NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 2NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 4NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 8NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 16NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 1NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 2NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 4NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 8NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset fashion_mnist -f GAT/fashion_mnist-graph-types --graph_type 16NNFeatures --n_heads 1

python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type RAG --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 1NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 2NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 4NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 8NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 16NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 1NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 2NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 4NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 8NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar10 -f GAT/cifar10-graph-types --graph_type 16NNFeatures --n_heads 1

python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type RAG --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 1NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 2NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 4NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 8NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 16NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 1NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 2NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 4NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 8NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset cifar100 -f GAT/cifar100-graph-types --graph_type 16NNFeatures --n_heads 1

python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type RAG --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 1NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 2NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 4NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 8NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 16NNSpatial --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 1NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 2NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 4NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 8NNFeatures --n_heads 1
python3 train-model.py -m GAT --dataset stl10 -f GAT/stl10-graph-types --graph_type 16NNFeatures --n_heads 1
